import os

class Config(object):
    # setting a secret key to be used by flask to generate tokens by flask-WTF
    # The key can be generated by the os or use the hardcoded defined key
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'this-key-is-totally-hard'